site_name: GCES-24.1 Debian
site_description: Documentação da disciplina de GCES 24.1 do grupo Debian

repo_name: Debian-GCES-24.1
repo_url: https://github.com/Mylena-angelica/Debian-GCES-24.1
site_url: https://mylena-angelica.github.io/GCES-24.1/

copyright: Copyright &copy; 2024 Debian GCES 24.1  

theme:
  name: material
  language: pt-BR
  logo: img\logo-debian.png
  favicon: img\icon-debian.png
  icon:
    repo: fontawesome/brands/github-alt
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - content.action.edit
    - content.action.view
    - navigation.top
    - content.tabs.link
    - content.code.annotation
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: red
      toggle:
        icon: material/weather-night
        name: Modo noturno
    - scheme: slate
      primary: red
      toggle:
        icon: material/weather-sunny
        name: Modo claro

extra_css:
  - stylesheets/extra.css
extra:
  generator: false

nav:
  - Home: index.md
  - Sprint 1:
    - Sprint Planning: sprint1\sprintPlanning1.md
    - Ana Luíza: sprint1\anaLuiza1.md
    - Hellen: sprint1\hellen1.md
    - Ingrid: sprint1\ingrid1.md
    - Leonardo: sprint1\leonardo1.md
    - Mylena: sprint1\mylena1.md
  - Sprint 2:
    - Sprint Planning: sprint2\sprintPlanning2.md
    - Ana Luíza: sprint2\anaLuiza2.md
    - Bruno: sprint2\bruno2.md
    - Guilherme: sprint2\guilherme2.md
    - Hellen: sprint2\hellen2.md
    - Henrique: sprint2\henrique.md
    - Igor: sprint2\igor2.md
    - Ingrid: sprint2\ingrid2.md
    - João: sprint2\joao2.md
    - Leonardo: sprint2\leonardo2.md
    - Luana: sprint2\luana2.md
    - Marcelo: sprint2\marcelo2.md
    - Mylena: sprint2\mylena2.md
  - Sprint 3:
    - Ana Luíza: sprint3\anaLuiza3.md    
    - Bruno: sprint3\bruno3.md  
    - Hellen: sprint3\hellen3.md
    - Henrique: sprint3\henrique3.md
    - Igor: sprint3\igor3.md
    - Ingrid: sprint3\ingrid3.md  
    - Leonardo: sprint3\leonardo3.md
    - Luana: sprint3\luana3.md  
    - Mylena: sprint3\mylena3.md  
    - João: sprint3\joao3.md
  - Sprint 4:
    - Ana Luíza: sprint4\anaLuiza4.md
    #- Bruno: sprint4\bruno4.md
    - Guilherme: sprint4\guilherme4.md
    - Hellen: sprint4\hellen4.md
    - Henrique: sprint4\henriqu.md
    - Igor: sprint4\igor4md
    - Ingrid: sprint4\ingrid4.md
    - João: sprint4\joao4.md
    - Leonardo: sprint4\leonardo4.md
    - Luana: sprint4\luana4.md
    - Mylena: sprint4\mylena4.md
  - Tutoriais:
    - Nova versão Upstream: tutoriais\atualizacao_upstream.md
    - Erros comuns na atualização upstream: tutoriais\erro_atualizacao_upstream.md
